export const brand = [
    {
        "name":"Royal Enfield",
        "img":"./assets/RE.png"
    },
    {
        "name":"Bajaj",
        "img":"./assets/bajaj.png"
    },
    {
        "name":"BMW",
        "img":"./assets/BMW.png"
    },
    {
        "name":"Harley Davidson",
        "img":"./assets/harley-davidson.png"
    },
    {
        "name":"Honda",
        "img":"./assets/Honda.png"
    },
    {
        "name":"KTM",
        "img":"./assets/KTM.png"
    },
    {
        "name":"Hero",
        "img":"./assets/hero.png"
    },
    {
        "name":"Ola",
        "img":"./assets/ola.png"
    },
    {
        "name":"Suzuki",
        "img":"./assets/Suzuki.png"
    },
    {
        "name":"Triumph",
        "img":"./assets/triumph.png"
    },
    {
        "name":"TVS",
        "img":"./assets/TVS.png"
    },
    {
        "name":"Yamaha",
        "img":"./assets/Yamaha.png"
    },
    {
        "name":"Java",
        "img":"./assets/Java.png"
    },
    {
        "name":"Mahindra",
        "img":"./assets/Mahindra.png"
    },
    {
        "name":"Revolt",
        "img":"./assets/Revolt.png"
    }
]